version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static

    depends_on:
      - web
  db:
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345
        POSTGRES_DB: postgres
    volumes:
        - /dbdata:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn reactexample.wsgi -b 0.0.0.0:8000"
  
    volumes:
      - .:/code
      - /static:/static
    expose:
      - "8000"
    depends_on:
      - db

 

