FROM python:3
MAINTAINER Lyudmyla Kaluzhynova "kaluzhynova@gmail.com"

 ENV PYTHONUNBUFFERED 1
 RUN mkdir /code
 WORKDIR /code
 ADD requirements.txt /code/
 RUN pip install -r requirements.txt
 ADD . /code/
 EXPOSE 80
 CMD [ "python", "./manage.py", "runserver", "0.0.0.0:8000"]
